# Generated by Django 3.2.20 on 2023-07-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('itemDoMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.itemdomenu')),
            ],
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('itemdomenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.itemdomenu')),
                ('tamanho', models.IntegerField()),
            ],
            bases=('polls.itemdomenu',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('itemdomenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.itemdomenu')),
                ('tamanho', models.IntegerField()),
                ('bordaRecheada', models.BooleanField()),
            ],
            bases=('polls.itemdomenu',),
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardapio', models.ManyToManyField(to='polls.Cardapio')),
                ('carrinho', models.ManyToManyField(to='polls.Carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('FINALIZADO', 'Finalizado'), ('A_CAMINHO', 'A caminho'), ('PREPARANDO_PEDIDO', 'Preparando pedido')], max_length=20)),
                ('cliente', models.ManyToManyField(to='polls.Cliente')),
                ('itemsDePedido', models.ManyToManyField(to='polls.ItemPedido')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ManyToManyField(to='polls.Endereco'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.cliente'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='itensDoMenu',
            field=models.ManyToManyField(to='polls.ItemPedido'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='ItemsDoMenu',
            field=models.ManyToManyField(to='polls.ItemDoMenu'),
        ),
    ]
